export const BOARD_PROPERTIES = [
  { id: 0, name: "Start", type: "corner" },
  { id: 1, name: "Rahova", color: "#845031", type: "property", price: 60 },
  { id: 2, name: "Cufarul Comunitatii", type: "chest" },
  { id: 3, name: "Giulesti", color: "#845031", type: "property", price: 60 },
  { id: 4, name: "Impozit pe Venit", type: "tax", price: 200 },
  { id: 5, name: "Gara de Progresul", type: "railroad", price: 200 },
  { id: 6, name: "Vitan", color: "#c0e0f9", type: "property", price: 100 },
  { id: 7, name: "Sansa", type: "chance" },
  { id: 8, name: "Pantelimon", color: "#c0e0f9", type: "property", price: 100 },
  { id: 9, name: "Berceni", color: "#c0e0f9", type: "property", price: 120 },
  { id: 10, name: "Inchisoare | Vizita", type: "corner" },
  { id: 11, name: "Titan", color: "#b63785", type: "property", price: 140 },
  { id: 12, name: "Uzina Electrica", type: "utility", price: 150 },
  { id: 13, name: "Colentina", color: "#b63785", type: "property", price: 140 },
  { id: 14, name: "Tei", color: "#b63785", type: "property", price: 160 },
  { id: 15, name: "Gara Obor", type: "railroad", price: 200 },
  { id: 16, name: "B-dul Timisoara", color: "#d39423", type: "property", price: 180 },
  { id: 17, name: "Cufarul Comunitatii", type: "chest" },
  { id: 18, name: "B-dul Brasov", color: "#d39423", type: "property", price: 180 },
  { id: 19, name: "Drumul Taberei", color: "#d39423", type: "property", price: 200 },
  { id: 20, name: "Parcare", type: "corner" },
  { id: 21, name: "B-dul Carol", color: "#c3141b", type: "property", price: 220 },
  { id: 22, name: "Sansa", type: "chance" },
  { id: 23, name: "B-dul Kogalniceanu", color: "#c3141b", type: "property", price: 220 },
  { id: 24, name: "B-dul Eroilor", color: "#c3141b", type: "property", price: 240 },
  { id: 25, name: "Gara Basarab", type: "railroad", price: 200 },
  { id: 26, name: "B-dul Titulescu", color: "#fdee01", type: "property", price: 260 },
  { id: 27, name: "B-dul 1 Mai", color: "#fdee01", type: "property", price: 260 },
  { id: 28, name: "Uzina de Apa", type: "utility", price: 150 },
  { id: 29, name: "Calea Dorobantilor", color: "#fdee01", type: "property", price: 280 },
  { id: 30, name: "Du-te la Inchisoare", type: "corner" },
  { id: 31, name: "Piata Unirii", color: "#5aa757", type: "property", price: 300 },
  { id: 32, name: "Cotroceni", color: "#5aa757", type: "property", price: 300 },
  { id: 33, name: "Cufarul Comunitatii", type: "chest" },
  { id: 34, name: "Calea Victoriei", color: "#5aa757", type: "property", price: 320 },
  { id: 35, name: "Gara de Nord", type: "railroad", price: 200 },
  { id: 36, name: "Sansa", type: "chance" },
  { id: 37, name: "B-dul Magheru", color: "#1166b0", type: "property", price: 350 },
  { id: 38, name: "Taxa de Lux", type: "tax", price: 100 },
  { id: 39, name: "B-dul Primaverii", color: "#1166b0", type: "property", price: 400 },
];


// export const BOARD_PROPERTIES = [
//   { id: 0, name: "GO", type: "special" },
//   { id: 1, name: "Mediterranean Avenue", color: "brown", price: 60 },
//   { id: 2, name: "Community Chest", type: "chest" },
//   { id: 3, name: "Baltic Avenue", color: "brown", price: 60 },
//   { id: 4, name: "Income Tax", type: "tax", price: 200 },
//   { id: 5, name: "Reading Railroad", type: "railroad", price: 200 },
//   { id: 6, name: "Oriental Avenue", color: "lightblue", price: 100 },
//   { id: 7, name: "Chance", type: "chance" },
//   { id: 8, name: "Vermont Avenue", color: "lightblue", price: 100 },
//   { id: 9, name: "Connecticut Avenue", color: "lightblue", price: 120 },
//   { id: 10, name: "Jail", type: "special" },
//   { id: 11, name: "St. Charles Place", color: "pink", price: 140 },
//   { id: 12, name: "Electric Company", type: "utility", price: 150 },
//   { id: 13, name: "States Avenue", color: "pink", price: 140 },
//   { id: 14, name: "Virginia Avenue", color: "pink", price: 160 },
//   { id: 15, name: "Pennsylvania Railroad", type: "railroad", price: 200 },
//   { id: 16, name: "St. James Place", color: "orange", price: 180 },
//   { id: 17, name: "Community Chest", type: "chest" },
//   { id: 18, name: "Tennessee Avenue", color: "orange", price: 180 },
//   { id: 19, name: "New York Avenue", color: "orange", price: 200 },
//   { id: 20, name: "Free Parking", type: "special" },
//   { id: 21, name: "Kentucky Avenue", color: "red", price: 220 },
//   { id: 22, name: "Chance", type: "chance" },
//   { id: 23, name: "Indiana Avenue", color: "red", price: 220 },
//   { id: 24, name: "Illinois Avenue", color: "red", price: 240 },
//   { id: 25, name: "B. & O. Railroad", type: "railroad", price: 200 },
//   { id: 26, name: "Atlantic Avenue", color: "yellow", price: 260 },
//   { id: 27, name: "Ventnor Avenue", color: "yellow", price: 260 },
//   { id: 28, name: "Water Works", type: "utility", price: 150 },
//   { id: 29, name: "Marvin Gardens", color: "yellow", price: 280 },
//   { id: 30, name: "Go To Jail", type: "special" },
//   { id: 31, name: "Pacific Avenue", color: "green", price: 300 },
//   { id: 32, name: "North Carolina Avenue", color: "green", price: 300 },
//   { id: 33, name: "Community Chest", type: "chest" },
//   { id: 34, name: "Pennsylvania Avenue", color: "green", price: 320 },
//   { id: 35, name: "Short Line Railroad", type: "railroad", price: 200 },
//   { id: 36, name: "Chance", type: "chance" },
//   { id: 37, name: "Park Place", color: "darkblue", price: 350 },
//   { id: 38, name: "Luxury Tax", type: "tax", price: 100 },
//   { id: 39, name: "Boardwalk", color: "darkblue", price: 400 },
// ];